app = 'prata'
primary_region = 'gru'

[build]
dockerfile = "Dockerfile"

[env]
PORT = '8080'
TZ = 'UTC'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = "256mb"
cpu_kind = "shared"
cpus = 1

[processes]
app = "/app/bin/api"
